name: Production CI/CD
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: powershell
env:
  PUBLISH_FOLDER: D:\GitHubRunner\Publish
  PACKAGE_FOLDER: D:\GitHubRunner\Packages
  PACKAGE_NAME: WebApi.zip
  REPORT_FOLDER: D:\GitHubRunner\Reports
  SONAR_REPORT: D:\GitHubRunner\Reports\Sonar
  COVERAGE_REPORT: D:\GitHubRunner\Reports\Coverage
  TEST_REPORT: D:\GitHubRunner\Reports\TestResults
  DATABASE_FOLDER: D:\GitHubRunner\Database
  
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      ####################################################
      # Checkout
      ####################################################
      - name: Checkout Repository
        uses: actions/checkout@v4
  cleanup:
    needs: checkout
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      ####################################################
      # Create Report Folders
      ####################################################
      - name: Create Report Folders
        run: |
          New-Item `
            -ItemType Directory `
            -Force `
            -Path "$env:REPORT_FOLDER" | Out-Null
      
          New-Item `
            -ItemType Directory `
            -Force `
            -Path "$env:SONAR_REPORT" | Out-Null
      
          New-Item `
            -ItemType Directory `
            -Force `
            -Path "$env:COVERAGE_REPORT" | Out-Null
      
          New-Item `
            -ItemType Directory `
            -Force `
            -Path "$env:TEST_REPORT" | Out-Null

          New-Item `
            -ItemType Directory `
            -Force `
            -Path D:\GitHubRunner\Database | Out-Null

      ####################################################
      # Cleanup Old Files
      ####################################################
      - name: Cleanup Old Files
        shell: powershell
        run: |
      
            Remove-Item D:\GitHubRunner\Publish\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item D:\GitHubRunner\Packages\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item D:\GitHubRunner\Reports\* -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item D:\GitHubRunner\Database\* -Recurse -Force -ErrorAction SilentlyContinue
        
      
            New-Item -ItemType Directory -Force -Path D:\GitHubRunner\Publish | Out-Null
            New-Item -ItemType Directory -Force -Path D:\GitHubRunner\Packages | Out-Null
            New-Item -ItemType Directory -Force -Path D:\GitHubRunner\Reports\TestResults | Out-Null
            New-Item -ItemType Directory -Force -Path D:\GitHubRunner\Reports\Coverage | Out-Null
            New-Item -ItemType Directory -Force -Path D:\GitHubRunner\Reports\Sonar | Out-Null
            New-Item -ItemType Directory -Force -Path D:\GitHubRunner\Database | Out-Null
  restore:
    needs: cleanup
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      ####################################################
      # Verify SDK
      ####################################################
      - name: Verify .NET SDK
        run: |
          dotnet --info
          dotnet --list-sdks
  
      ####################################################
      # Restore
      ####################################################
      - name: Restore NuGet Packages
        run: |
          dotnet restore
  build:
    needs: restore
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      ####################################################
      # Build
      ####################################################
      - name: Build Solution
        run: |
          dotnet build WebApi.sln --configuration Release --no-restore
