name: 01 - Build

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: powershell

env:
  PUBLISH_FOLDER: D:\GitHubRunner\Publish
  PACKAGE_FOLDER: D:\GitHubRunner\Packages
  PACKAGE_NAME: WebApi.zip
  REPORT_FOLDER: D:\GitHubRunner\Reports
  SONAR_REPORT: D:\GitHubRunner\Reports\Sonar
  COVERAGE_REPORT: D:\GitHubRunner\Reports\Coverage
  TEST_REPORT: D:\GitHubRunner\Reports\TestResults
  DATABASE_FOLDER: D:\GitHubRunner\Database

jobs:

  build:

    runs-on: self-hosted

    steps:

    ####################################################
    # Checkout Repository
    ####################################################
    - name: Checkout Repository
      uses: actions/checkout@v4

    ####################################################
    # Verify Repository
    ####################################################
    - name: Verify Repository
      run: |
        Write-Host ""
        Write-Host "Repository Contents"
        Get-ChildItem -Recurse

    ####################################################
    # Cleanup Old Files
    ####################################################
    - name: Cleanup Runner Folders
      run: |

        Remove-Item "$env:PUBLISH_FOLDER\*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item "$env:PACKAGE_FOLDER\*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item "$env:REPORT_FOLDER\*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item "$env:DATABASE_FOLDER\*" -Recurse -Force -ErrorAction SilentlyContinue

    ####################################################
    # Create Runner Folders
    ####################################################
    - name: Create Runner Folders
      run: |

        New-Item -ItemType Directory -Force -Path $env:PUBLISH_FOLDER | Out-Null
        New-Item -ItemType Directory -Force -Path $env:PACKAGE_FOLDER | Out-Null
        New-Item -ItemType Directory -Force -Path $env:REPORT_FOLDER | Out-Null
        New-Item -ItemType Directory -Force -Path $env:SONAR_REPORT | Out-Null
        New-Item -ItemType Directory -Force -Path $env:COVERAGE_REPORT | Out-Null
        New-Item -ItemType Directory -Force -Path $env:TEST_REPORT | Out-Null
        New-Item -ItemType Directory -Force -Path $env:DATABASE_FOLDER | Out-Null

    ####################################################
    # Verify .NET SDK
    ####################################################
    - name: Verify .NET SDK
      run: |

        dotnet --info
        dotnet --version
        dotnet --list-sdks

    ####################################################
    # Verify Solution
    ####################################################
    - name: Verify Solution
      run: |

        if (!(Test-Path ".\WebApi.sln"))
        {
            throw "WebApi.sln not found."
        }

        Write-Host "Solution Found"

    ####################################################
    # Restore Packages
    ####################################################
    - name: Restore NuGet Packages
      run: |

        dotnet restore WebApi.sln

        if($LASTEXITCODE -ne 0)
        {
            throw "NuGet Restore Failed."
        }

    ####################################################
    # Copy Database Scripts
    ####################################################
    - name: Copy Database Scripts
      run: |

        if(Test-Path ".\DatabaseScript")
        {
            Copy-Item `
                ".\DatabaseScript\*.sql" `
                "$env:DATABASE_FOLDER" `
                -Force

            Write-Host "Database scripts copied successfully."
        }
        else
        {
            Write-Host "DatabaseScript folder not found."
        }

    ####################################################
    # Verify Database Scripts
    ####################################################
    - name: Verify Database Scripts
      run: |

        Get-ChildItem "$env:DATABASE_FOLDER"

    ####################################################
    # Build Solution
    ####################################################
    - name: Build Solution
      run: |

        dotnet build WebApi.sln `
            --configuration Release `
            --no-restore

        if($LASTEXITCODE -ne 0)
        {
            throw "Build Failed."
        }

    ####################################################
    # Verify Build
    ####################################################
    - name: Verify Build
      run: |

        Write-Host ""
        Write-Host "======================================"
        Write-Host "Build Completed Successfully"
        Write-Host "======================================"

  test-sonar:
    needs: build

    runs-on: self-hosted

    steps:

    ####################################################
    # Checkout
    ####################################################
    - name: Checkout Repository
      uses: actions/checkout@v4

    ####################################################
    # Restore
    ####################################################
    - name: Restore Packages
      run: |
        dotnet restore WebApi.sln

        if ($LASTEXITCODE -ne 0)
        {
            throw "NuGet Restore Failed."
        }

    ####################################################
    # Sonar Begin
    ####################################################
    - name: Sonar Begin
      run: |

        dotnet sonarscanner begin `
          /k:"WebApi" `
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.vstest.reportsPaths="$env:TEST_REPORT\*.trx" `
          /d:sonar.cs.opencover.reportsPaths="$env:COVERAGE_REPORT\coverage.opencover.xml"

        if ($LASTEXITCODE -ne 0)
        {
            throw "Sonar Begin Failed."
        }

    ####################################################
    # Build
    ####################################################
    - name: Build Solution
      run: |

        dotnet build WebApi.sln `
          --configuration Release `
          --no-restore

        if ($LASTEXITCODE -ne 0)
        {
            throw "Build Failed."
        }

    ####################################################
    # Unit Test
    ####################################################
    - name: Run Unit Tests
      run: |

        dotnet test .\WebApi.Test\WebApi.Test.csproj `
          --configuration Release `
          --no-build `
          --logger "trx;LogFileName=TestResults.trx" `
          --results-directory "$env:TEST_REPORT" `
          /p:CollectCoverage=true `
          /p:CoverletOutput="$env:COVERAGE_REPORT\" `
          /p:CoverletOutputFormat=opencover

        if ($LASTEXITCODE -ne 0)
        {
            throw "Unit Tests Failed."
        }

    ####################################################
    # Verify Coverage
    ####################################################
    - name: Verify Coverage File
      run: |

        if (!(Test-Path "$env:COVERAGE_REPORT\coverage.opencover.xml"))
        {
            throw "Coverage file not found."
        }

    ####################################################
    # Sonar End
    ####################################################
    - name: Sonar End
      run: |

        dotnet sonarscanner end `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

        if ($LASTEXITCODE -ne 0)
        {
            throw "Sonar End Failed."
        }
  ####################################################
  # Generate HTML Report
  ####################################################
    - name: Generate HTML Report
      run: |
    
        New-Item `
          -ItemType Directory `
          -Force `
          -Path "$env:SONAR_REPORT" | Out-Null
    
        $Status = "Passed"

        $html = @"
        <html>
        <head>
        <title>Sonar Report</title>
        </head>
        
        <body>
        
        <h2>SonarQube Report</h2>
        
        <table border="1">
        <tr>
        <th>Project</th>
        <td>WebApi</td>
        </tr>
        
        <tr>
        <th>Quality Gate</th>
        <td>$Status</td>
        </tr>
        
        <tr>
        <th>Date</th>
        <td>$(Get-Date)</td>
        </tr>
        </table>
        
        </body>
        </html>
        "@
        
        $html | Out-File `
            "$env:SONAR_REPORT\SonarReport.html" `
            -Encoding UTF8

    ####################################################
    # Generate PDF
    ####################################################
    - name: Generate PDF Report
      run: |

        if (!(Test-Path "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"))
        {
            throw "wkhtmltopdf not installed."
        }

        & "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" `
        "$env:SONAR_REPORT\SonarReport.html" `
        "$env:SONAR_REPORT\SonarReport.pdf"

    ####################################################
    # Coverage Report
    ####################################################
    - name: Generate Coverage Report
      run: |

        reportgenerator `
          -reports:"$env:COVERAGE_REPORT\coverage.opencover.xml" `
          -targetdir:"$env:COVERAGE_REPORT\Html" `
          -reporttypes:"Html;HtmlSummary"

    ####################################################
    # Zip Reports
    ####################################################
    - name: Zip Reports
      run: |

        if(Test-Path "$env:PACKAGE_FOLDER\Reports.zip")
        {
            Remove-Item "$env:PACKAGE_FOLDER\Reports.zip" -Force
        }

        Compress-Archive `
          -Path "$env:REPORT_FOLDER\*" `
          -DestinationPath "$env:PACKAGE_FOLDER\Reports.zip"

        if (!(Test-Path "$env:PACKAGE_FOLDER\Reports.zip"))
        {
            throw "Reports.zip not created."
        }

    ####################################################
    # Upload Reports
    ####################################################
    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: Reports
        path: |
          D:\GitHubRunner\Reports
          D:\GitHubRunner\Packages\Reports.zip

  package:
      needs: test-sonar
      runs-on: self-hosted
  
      steps:
  
      ####################################################
      # Checkout Repository
      ####################################################
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      ####################################################
      # Restore Packages
      ####################################################
      - name: Restore NuGet Packages
        run: |
  
          dotnet restore WebApi.sln
  
          if ($LASTEXITCODE -ne 0)
          {
              throw "NuGet Restore Failed."
          }
  
      ####################################################
      # Create Required Folders
      ####################################################
      - name: Create Package Folders
        run: |
  
          New-Item `
              -ItemType Directory `
              -Force `
              -Path "$env:PUBLISH_FOLDER" | Out-Null
  
          New-Item `
              -ItemType Directory `
              -Force `
              -Path "$env:PACKAGE_FOLDER" | Out-Null
  
          New-Item `
              -ItemType Directory `
              -Force `
              -Path "$env:DATABASE_FOLDER" | Out-Null
  
      ####################################################
      # Publish Application
      ####################################################
      - name: Publish Application
        run: |
  
          Remove-Item `
              "$env:PUBLISH_FOLDER\*" `
              -Recurse `
              -Force `
              -ErrorAction SilentlyContinue
  
          dotnet publish `
              .\WebApi\WebApi.csproj `
              --configuration Release `
              --output "$env:PUBLISH_FOLDER"
  
          if ($LASTEXITCODE -ne 0)
          {
              throw "Publish Failed."
          }
  
      ####################################################
      # Verify Publish
      ####################################################
      - name: Verify Publish
        run: |
  
          $Files = Get-ChildItem "$env:PUBLISH_FOLDER"
  
          if ($Files.Count -eq 0)
          {
              throw "Publish folder is empty."
          }
  
          Write-Host "Publish completed successfully."
  
      ####################################################
      # Copy Database Scripts
      ####################################################
      - name: Copy Database Scripts
        run: |
  
          if (!(Test-Path ".\DatabaseScript"))
          {
              throw "DatabaseScript folder not found."
          }
  
          Copy-Item `
              ".\DatabaseScript\*.sql" `
              "$env:DATABASE_FOLDER" `
              -Force
  
      ####################################################
      # Verify SQL Files
      ####################################################
      - name: Verify SQL Files
        run: |
  
          $SqlFiles = Get-ChildItem `
              "$env:DATABASE_FOLDER\*.sql"
  
          if ($SqlFiles.Count -eq 0)
          {
              throw "No SQL files found."
          }
  
          Write-Host ""
          Write-Host "Database Scripts"
  
          $SqlFiles | Format-Table Name,Length
  
      ####################################################
      # Remove Old ZIP Files
      ####################################################
      - name: Remove Existing Packages
        run: |
  
          if(Test-Path "$env:PACKAGE_FOLDER\$env:PACKAGE_NAME")
          {
              Remove-Item `
                  "$env:PACKAGE_FOLDER\$env:PACKAGE_NAME" `
                  -Force
          }
  
          if(Test-Path "$env:PACKAGE_FOLDER\Database.zip")
          {
              Remove-Item `
                  "$env:PACKAGE_FOLDER\Database.zip" `
                  -Force
          }
  
      ####################################################
      # Create Web Package
      ####################################################
      - name: Create Web Package
        run: |
  
          Compress-Archive `
              -Path "$env:PUBLISH_FOLDER\*" `
              -DestinationPath "$env:PACKAGE_FOLDER\$env:PACKAGE_NAME"
  
      ####################################################
      # Create Database Package
      ####################################################
      - name: Create Database Package
        run: |
  
          Compress-Archive `
              -Path "$env:DATABASE_FOLDER\*" `
              -DestinationPath "$env:PACKAGE_FOLDER\Database.zip"
  
      ####################################################
      # Verify Packages
      ####################################################
      - name: Verify Packages
        run: |
  
          if (!(Test-Path "$env:PACKAGE_FOLDER\$env:PACKAGE_NAME"))
          {
              throw "WebApi.zip not created."
          }
  
          if (!(Test-Path "$env:PACKAGE_FOLDER\Database.zip"))
          {
              throw "Database.zip not created."
          }
  
          Write-Host ""
          Write-Host "Deployment Packages"
          Write-Host "==============================="
  
          Get-ChildItem `
              "$env:PACKAGE_FOLDER" `
              | Format-Table Name,Length,LastWriteTime
  
      ####################################################
      # Upload Package Artifact
      ####################################################
      - name: Upload Deployment Packages
        uses: actions/upload-artifact@v4
        with:
          name: DeploymentPackages
          path: |
            D:\GitHubRunner\Packages\WebApi.zip
            D:\GitHubRunner\Packages\Database.zip
  
      ####################################################
      # Package Summary
      ####################################################
      - name: Package Summary
        run: |
  
          Write-Host ""
          Write-Host "======================================="
          Write-Host "Package Creation Completed Successfully"
          Write-Host "======================================="
          Write-Host "Application : $env:PACKAGE_FOLDER\$env:PACKAGE_NAME"
          Write-Host "Database    : $env:PACKAGE_FOLDER\Database.zip"
          Write-Host "======================================="
  copy-artifacts:
      needs: package
      runs-on: self-hosted
  
      steps:
  
      ####################################################
      # Checkout
      ####################################################
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      ####################################################
      # Download Package Artifacts
      ####################################################
      - name: Download Deployment Packages
        uses: actions/download-artifact@v4
        with:
          name: DeploymentPackages
          path: D:\GitHubRunner\Packages
  
      ####################################################
      # Verify Package Files
      ####################################################
      - name: Verify Package Files
        run: |
  
          if (!(Test-Path "$env:PACKAGE_FOLDER\WebApi.zip"))
          {
              throw "WebApi.zip not found."
          }
  
          if (!(Test-Path "$env:PACKAGE_FOLDER\Database.zip"))
          {
              throw "Database.zip not found."
          }
  
          Get-ChildItem "$env:PACKAGE_FOLDER"
  
      ####################################################
      # Verify Reports
      ####################################################
      - name: Verify Reports
        run: |
  
          if (!(Test-Path "$env:PACKAGE_FOLDER\Reports.zip"))
          {
              throw "Reports.zip not found."
          }
  
      ####################################################
      # Test SSH Connectivity
      ####################################################
      - name: Test SSH Connection
        run: |
  
          ssh `
            -v `
            -i "$env:SSH_KEY" `
            -o BatchMode=yes `
            -o StrictHostKeyChecking=no `
            $env:ANSIBLE_SERVER `
            "hostname && whoami && pwd"
  
      ####################################################
      # Copy Web Package
      ####################################################
      - name: Copy WebApi Package
        run: |
  
          powershell.exe `
            -ExecutionPolicy Bypass `
            -File D:\GitHubRunner\Scripts\CopyToAnsible.ps1
  
          if($LASTEXITCODE -ne 0)
          {
              throw "WebApi package copy failed."
          }
  
      ####################################################
      # Copy Reports
      ####################################################
      - name: Copy Sonar Reports
        run: |
  
          powershell.exe `
            -ExecutionPolicy Bypass `
            -File D:\GitHubRunner\Scripts\CopyReportsToAnsible.ps1
  
          if($LASTEXITCODE -ne 0)
          {
              throw "Reports copy failed."
          }
  
      ####################################################
      # Copy Database Package
      ####################################################
      - name: Copy Database Package
        run: |
  
          powershell.exe `
            -ExecutionPolicy Bypass `
            -File D:\GitHubRunner\Scripts\CopyDatabaseScriptToAnsible.ps1
  
          if($LASTEXITCODE -ne 0)
          {
              throw "Database package copy failed."
          }
  
      ####################################################
      # Verify Files on Ansible
      ####################################################
      - name: Verify Files on Ansible
        run: |
  
          ssh `
            -i "$env:SSH_KEY" `
            -o StrictHostKeyChecking=no `
            $env:ANSIBLE_SERVER `
            "
            echo '===== Web Package ====='
            ls -lh /opt/ansible/artifacts/latest
  
            echo ''
            echo '===== Database ====='
            ls -lh /opt/ansible/artifacts/Database/latest
  
            echo ''
            echo '===== Reports ====='
            ls -lh /opt/ansible/reports/latest
            "
  
      ####################################################
      # Deployment Summary
      ####################################################
      - name: Copy Summary
        run: |
  
          Write-Host ""
          Write-Host "==========================================="
          Write-Host "Artifacts copied successfully to Ansible"
          Write-Host "==========================================="
          Write-Host "WebApi.zip"
          Write-Host "Database.zip"
          Write-Host "Reports.zip"
          Write-Host "Destination Server : 172.31.37.164"
          Write-Host "==========================================="
