name: 02 - Test, Sonar & Reports

on:
  workflow_run:
    workflows: ["01 - Build"]
    types:
      - completed

defaults:
  run:
    shell: powershell

env:
  REPORT_FOLDER: D:\GitHubRunner\Reports
  SONAR_REPORT: D:\GitHubRunner\Reports\Sonar
  COVERAGE_REPORT: D:\GitHubRunner\Reports\Coverage
  TEST_REPORT: D:\GitHubRunner\Reports\TestResults
  PACKAGE_FOLDER: D:\GitHubRunner\Packages

jobs:

  test-sonar:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:

    ####################################################
    # Checkout
    ####################################################
    - name: Checkout Repository
      uses: actions/checkout@v4

    ####################################################
    # Restore
    ####################################################
    - name: Restore Packages
      run: |
        dotnet restore WebApi.sln

        if ($LASTEXITCODE -ne 0)
        {
            throw "NuGet Restore Failed."
        }

    ####################################################
    # Sonar Begin
    ####################################################
    - name: Sonar Begin
      run: |

        dotnet sonarscanner begin `
          /k:"WebApi" `
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.vstest.reportsPaths="$env:TEST_REPORT\*.trx" `
          /d:sonar.cs.opencover.reportsPaths="$env:COVERAGE_REPORT\coverage.opencover.xml"

        if ($LASTEXITCODE -ne 0)
        {
            throw "Sonar Begin Failed."
        }

    ####################################################
    # Build
    ####################################################
    - name: Build Solution
      run: |

        dotnet build WebApi.sln `
          --configuration Release `
          --no-restore

        if ($LASTEXITCODE -ne 0)
        {
            throw "Build Failed."
        }

    ####################################################
    # Unit Test
    ####################################################
    - name: Run Unit Tests
      run: |

        dotnet test .\WebApi.Test\WebApi.Test.csproj `
          --configuration Release `
          --no-build `
          --logger "trx;LogFileName=TestResults.trx" `
          --results-directory "$env:TEST_REPORT" `
          /p:CollectCoverage=true `
          /p:CoverletOutput="$env:COVERAGE_REPORT\" `
          /p:CoverletOutputFormat=opencover

        if ($LASTEXITCODE -ne 0)
        {
            throw "Unit Tests Failed."
        }

    ####################################################
    # Verify Coverage
    ####################################################
    - name: Verify Coverage File
      run: |

        if (!(Test-Path "$env:COVERAGE_REPORT\coverage.opencover.xml"))
        {
            throw "Coverage file not found."
        }

    ####################################################
    # Sonar End
    ####################################################
    - name: Sonar End
      run: |

        dotnet sonarscanner end `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

        if ($LASTEXITCODE -ne 0)
        {
            throw "Sonar End Failed."
        }
  ####################################################
  # Generate HTML Report
  ####################################################
    - name: Generate HTML Report
      run: |
    
        New-Item `
          -ItemType Directory `
          -Force `
          -Path "$env:SONAR_REPORT" | Out-Null
    
        $html = @"
          <html>
          <head>
          <title>Sonar Report</title>
          </head>
          
          <body>
          
          <h2>SonarQube Report</h2>
          
          <table border="1">
          
          <tr>
          <th>Project</th>
          <td>WebApi</td>
          </tr>
          
          <tr>
          <th>Date</th>
          <td>$(Get-Date)</td>
          </tr>
          
          </table>
          
          </body>
          
          </html>
          "@
    
        $html | Out-File `
          "$env:SONAR_REPORT\SonarReport.html" `
          -Encoding UTF8

    ####################################################
    # Generate PDF
    ####################################################
    - name: Generate PDF Report
      run: |

        if (!(Test-Path "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"))
        {
            throw "wkhtmltopdf not installed."
        }

        & "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" `
        "$env:SONAR_REPORT\SonarReport.html" `
        "$env:SONAR_REPORT\SonarReport.pdf"

    ####################################################
    # Coverage Report
    ####################################################
    - name: Generate Coverage Report
      run: |

        reportgenerator `
          -reports:"$env:COVERAGE_REPORT\coverage.opencover.xml" `
          -targetdir:"$env:COVERAGE_REPORT\Html" `
          -reporttypes:"Html;HtmlSummary"

    ####################################################
    # Zip Reports
    ####################################################
    - name: Zip Reports
      run: |

        if(Test-Path "$env:PACKAGE_FOLDER\Reports.zip")
        {
            Remove-Item "$env:PACKAGE_FOLDER\Reports.zip" -Force
        }

        Compress-Archive `
          -Path "$env:REPORT_FOLDER\*" `
          -DestinationPath "$env:PACKAGE_FOLDER\Reports.zip"

        if (!(Test-Path "$env:PACKAGE_FOLDER\Reports.zip"))
        {
            throw "Reports.zip not created."
        }

    ####################################################
    # Upload Reports
    ####################################################
    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: Reports
        path: |
          D:\GitHubRunner\Reports
          D:\GitHubRunner\Packages\Reports.zip
