name: 05 - Production Approval

on:
  workflow_run:
    workflows:
      - "01 - Build"
    types:
      - completed

defaults:
  run:
    shell: powershell

jobs:

  ####################################################
  # Send Approval Email
  ####################################################
  send-approval-email:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send Approval Request
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          secure: false

          subject: Production Deployment Approval Required

          from: GitHub CI/CD <${{ secrets.SMTP_USERNAME }}>

          to: ${{ secrets.EMAIL_TO }}

          body: |
            Production deployment is ready for approval.

            =======================================

            Repository : ${{ github.repository }}
            Branch     : ${{ github.event.workflow_run.head_branch }}
            Run Number : ${{ github.event.workflow_run.run_number }}

            =======================================

            Please review and approve the deployment.

            GitHub Actions:

            https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}

  ####################################################
  # Wait For Manual Approval
  ####################################################
  wait-for-approval:

    needs: send-approval-email

    runs-on: self-hosted

    environment:
      name: production

    steps:

      - name: Waiting For Approval
        run: |

          Write-Host ""
          Write-Host "========================================="
          Write-Host "Waiting for Production Approval..."
          Write-Host "========================================="

      - name: Approval Received
        run: |

          Write-Host ""
          Write-Host "========================================="
          Write-Host "Production Deployment Approved"
          Write-Host "========================================="
