name: Production CI/CD
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: powershell
  
jobs:
  approval:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
      - name: Send Approval Request
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
  
          subject: "Production Deployment Approval Required"
  
          to: avadhutap459@gmail.com
  
          from: GitHub CI/CD <${{ secrets.SMTP_USERNAME }}>
  
          secure: false
  
          body: |
            Production deployment is ready.
  
            Repository : ${{ github.repository }}
            Branch     : ${{ github.ref_name }}
            Build      : #${{ github.run_number }}
  
            Please approve the deployment in GitHub Actions.
  
            Workflow:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}  
  
