name: Build and Publish .NET 8 Application

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Build and Publish

    runs-on:
      - self-hosted
      - windows

    env:
      BUILD_CONFIGURATION: Release
      PUBLISH_TEMP: D:\PublishTemp
      PUBLISH_FOLDER: D:\Applications\MyAPI\Publish

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Display .NET Version
      shell: powershell
      run: |
        dotnet --info

    - name: Restore NuGet Packages
      run: |
        dotnet restore

    - name: Build Solution
      run: |
        dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Remove Previous Temporary Publish Folder
      shell: powershell
      run: |
        if (Test-Path "${{ env.PUBLISH_TEMP }}")
        {
            Remove-Item "${{ env.PUBLISH_TEMP }}" -Recurse -Force
        }

    - name: Publish Application
      run: |
        dotnet publish `
        --configuration ${{ env.BUILD_CONFIGURATION }} `
        --output "${{ env.PUBLISH_TEMP }}" `
        --no-build

    - name: Create Publish Folder if Not Exists
      shell: powershell
      run: |
        if (!(Test-Path "${{ env.PUBLISH_FOLDER }}"))
        {
            New-Item `
              -ItemType Directory `
              -Path "${{ env.PUBLISH_FOLDER }}"
        }

    - name: Clean Existing Publish Folder
      shell: powershell
      run: |
        Get-ChildItem "${{ env.PUBLISH_FOLDER }}" -Force -ErrorAction SilentlyContinue |
        Remove-Item -Recurse -Force

    - name: Copy Published Files
      shell: powershell
      run: |
        Copy-Item `
          "${{ env.PUBLISH_TEMP }}\*" `
          "${{ env.PUBLISH_FOLDER }}" `
          -Recurse `
          -Force

    - name: Display Published Files
      shell: powershell
      run: |
        Get-ChildItem "${{ env.PUBLISH_FOLDER }}"

    - name: Cleanup Temporary Publish Folder
      shell: powershell
      run: |
        if (Test-Path "${{ env.PUBLISH_TEMP }}")
        {
            Remove-Item "${{ env.PUBLISH_TEMP }}" -Recurse -Force
        }

    - name: Deployment Completed
      shell: powershell
      run: |
        Write-Host ""
        Write-Host "======================================="
        Write-Host " Build Successful"
        Write-Host " Publish Successful"
        Write-Host " Files copied successfully"
        Write-Host " Location : ${{ env.PUBLISH_FOLDER }}"
        Write-Host "======================================="
