name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: self-hosted

    env:
      PUBLISH_FOLDER: D:\GitHubRunner\Publish
      PACKAGE_FOLDER: D:\GitHubRunner\Packages
      PACKAGE_NAME: WebApi.zip

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Packages
        run: |
          dotnet restore

      - name: Build Application
        run: |
          dotnet build --configuration Release --no-restore

      - name: Execute Unit Tests
        run: |
          dotnet test --configuration Release --no-build

      - name: Publish Application
        run: |
          dotnet publish -c Release -o "${{ env.PUBLISH_FOLDER }}"

      - name: Create ZIP Package
        shell: powershell
        run: |
          Compress-Archive `
            -Path "${{ env.PUBLISH_FOLDER }}\*" `
            -DestinationPath "${{ env.PACKAGE_FOLDER }}\${{ env.PACKAGE_NAME }}" `
            -Force

      - name: Copy Package to Ansible
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass `
          -File D:\GitHubRunner\Scripts\CopyToAnsible.ps1

      - name: Deploy using Ansible
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass `
          -File D:\GitHubRunner\Scripts\Deploy.ps1
