name: Publish DotNet Application

on:

  push:

    branches:

      - master

jobs:

  publish:

    runs-on:

      - self-hosted

      - windows

    steps:

      - name: Checkout Source

        uses: actions/checkout@v4

      - name: Setup Dotnet

        uses: actions/setup-dotnet@v4

        with:

          dotnet-version: 8.0.x

      - name: Restore

        run: dotnet restore

      - name: Build

        run: dotnet build --configuration Release --no-restore

      - name: Publish

        run: |

          dotnet publish `
          --configuration Release `
          --output D:\PublishTemp

      - name: Remove Old Publish

        shell: powershell

        run: |

          if(Test-Path "D:\Applications\MyAPI\Publish")
          {
             Remove-Item "D:\Applications\MyAPI\Publish\*" -Recurse -Force
          }

      - name: Copy Publish Files

        shell: powershell

        run: |

          Copy-Item `
          D:\PublishTemp\* `
          D:\Applications\MyAPI\Publish `
          -Recurse `
          -Force

      - name: Clean Temp

        shell: powershell

        run: |

          Remove-Item D:\PublishTemp -Recurse -Force
