name: Build and Deploy WebApi

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: '8.0.x'
  PUBLISH_FOLDER: C:\Deployment\Publish

jobs:

  BuildDeploy:

    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore WebApi.sln

    - name: Build
      run: dotnet build WebApi.sln --configuration Release --no-restore

    - name: Unit Test
      run: dotnet test WebApi.Test/WebApi.Test.csproj --configuration Release --no-build

    - name: Clean Publish Folder
      shell: cmd
      run: |
        if exist "C:\Deployment\Publish" rmdir /S /Q "C:\Deployment\Publish"
        mkdir "C:\Deployment\Publish"

    - name: Publish API
      shell: cmd
      run: |
        dotnet publish WebApi\WebApi.csproj ^
          --configuration Release ^
          --output C:\Deployment\Publish

    - name: Verify Publish
      shell: cmd
      run: |
        dir C:\Deployment\Publish

    - name: Deploy using MSDeploy
      shell: cmd
      run: |
        "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ^
        -verb:sync ^
        -source:contentPath="C:\Deployment\Publish" ^
        -dest:contentPath="C:\Websites\WebApi",computerName="https://172.31.10.193:8172/msdeploy.axd?site=WebApi",userName="WEBSERVER01\deployuser",password="NewStrongPassword@123",authType=Basic ^
        -enableRule:AppOffline ^
        -useChecksum ^
        -retryAttempts:5 ^
        -retryInterval:3000 ^
        -allowUntrusted

    - name: Verify Deployment
      shell: cmd
      run: |
        echo Deployment Completed
