name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show PATH
        shell: pwsh
        run: |
          $env:PATH

      - name: Locate dotnet
        shell: pwsh
        run: |
          where.exe dotnet

      - name: Show .NET Version
        shell: pwsh
        run: |
          dotnet --version

      - name: List SDKs
        shell: pwsh
        run: |
          dotnet --list-sdks
