name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Display Hostname
        run: hostname

      - name: Show .NET Version
        run: dotnet --version

      - name: Show Current Directory
        run: pwd
